name: Continous Delivery Dispatch

on:
  workflow_dispatch:

jobs:
  build-api:
    uses: MikkelRLarsenPersonalOrganization/InitalRepo/.github/workflows/AnotherCD.yml@main
    with:
      image-name: my-api
      docker-context: src/CiCd
